import mongoose from 'mongoose';
import crypto from 'crypto';

const teamSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Team name is required'],
      trim: true,
      maxlength: [50, 'Team name cannot exceed 50 characters'],
    },
    hackathon: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Hackathon',
      required: true,
    },
    leader: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    members: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    /**
     * Unique 6-character alphanumeric join code (e.g. "X7K2QP").
     * Generated by generateJoinCode() util. Scoped to {code, hackathon}.
     * Team leader can regenerate this code at any time before submission.
     */
    joinCode: {
      type: String,
      required: true,
      uppercase: true,
      length: 6,
    },
    // Whether the team has submitted a project
    hasSubmitted: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// Compound unique index: joinCode must be unique within a hackathon
teamSchema.index({ joinCode: 1, hackathon: 1 }, { unique: true });

const Team = mongoose.model('Team', teamSchema);
export default Team;
